# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  # On a manual run.
  workflow_dispatch:
    inputs:
        environment:
          description: 'Environment to run tests against'
          type: environment
          required: true
  
  # On a push to a branch.
  push:
    branches: [ "main" ]
    
  # On a pull request to a branch.
  pull_request:
    branches: [ "main" ]
    
env:
  # System
  TERM: xterm

  # Artifact Storage
  ARTIFACT_STORAGE_AWS_ACCESS_KEY_ID: "${{ secrets.ARTIFACT_STORAGE_AWS_ACCESS_KEY_ID }}"
  ARTIFACT_STORAGE_AWS_SECRET_ACCESS_KEY: "${{ secrets.ARTIFACT_STORAGE_AWS_SECRET_ACCESS_KEY }}"
  ARTIFACT_STORAGE_AWS_S3_BUCKET: "greenrestorationireland"
  ARTIFACT_STORAGE_AWS_REGION: "eu-west-1"
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment:  $environment
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm install -g @angular/cli
    - run: npm run build --if-present
    - run: ls -s -h
    - name: Upload Artifacts
      run: |
        aws sts get-caller-identity
        aws s3 sync ./dist/testapp s3://${{ env.ARTIFACT_STORAGE_AWS_S3_BUCKET }}/${{ steps.workflow-info.outputs.run-artifact-dir }} --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ env.ARTIFACT_STORAGE_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ env.ARTIFACT_STORAGE_AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ env.ARTIFACT_STORAGE_AWS_REGION }}
